"""
ELENA: EvaLuator of tunnElliNg Actions

A software for fast and precise computation of first order phase transitions 
and gravitational waves production in particle physics models.

ELENA is an open-source Python package designed to compute the full evolution 
of first-order phase transitions in the early universe generated by particle 
physics models. The core is based on a vectorized implementation of the 
tunnelling potential formalism for fast computation of finite-temperature 
tunnelling actions and resulting gravitational wave spectra.
"""

__version__ = '1.0'
__author__ = 'Francesco Costa, Jaime Hoefken Zink, Michele Lucente, Silvia Pascoli, Salvador Rosauro-Alcaraz'
__email__ = 'francesco.costa@matfyz.cuni.cz, jaime.hoefkenzink@ncbj.gov.pl, michele.lucente@unibo.it, silvia.pascoli@unibo.it, rosauroa@bo.infn.it'

__all__ = [
    'model',
    'espinosa', 
    'temperatures',
    'GWparams',
    'utils'
]